SELECT DISTINCT (SELECT MAX(G2.COD_GRADE)
                  FROM GRADE G2
                  WHERE G2.COD_CURSO = G1.COD_CURSO
                ) AS COD_GRADE
  FROM GRADE G1
  WHERE G1.COD_CURSO = :COD_CURSO
